### ISSUE TITLE
raml-to-jaxrs build error

### ISSUE THREAD

**Issue by aprodhomme** [mulesoft/raml-for-jax-rs#31]
Hi!

Since this day, the example projet using the raml-jaxrs-maven-plugin pluggin won't build anymore, and so my project.

Here is the error : 

[ERROR] Failed to execute goal org.raml.plugins:raml-jaxrs-maven-plugin:1.3.2-SN
APSHOT:generate (default) on project raml-jaxrs-jersey-example: Execution defaul
t of goal org.raml.plugins:raml-jaxrs-maven-plugin:1.3.2-SNAPSHOT:generate faile
d: An API incompatibility was encountered while executing org.raml.plugins:raml-
jaxrs-maven-plugin:1.3.2-SNAPSHOT:generate: java.lang.NoSuchMethodError: com.fas
terxml.jackson.databind.MappingIterator.getCurrentLocation()Lcom/fasterxml/jacks
on/core/JsonLocation;

It seems a new snapshot of raml-parser has been deployed and a dependency to com.fasterxml.jackson.core >> jackson-databind has been replaced by            com.fasterxml.jackson.module >> jackson-module-jsonSchema

https://github.com/raml-org/raml-java-parser/commit/faecb9bbc3f9005a87c46182c817992ec862932d

Do you have any idea when the pluggin raml-to-jaxrs will be ready to use the new version of the raml-parser?

For now, I'm using the lastest timestamped snapshot version which is still working with the pluggin (0.9-20141227.230728-71)

Thanks.

**Comment by petrochenko-pavel-a** [comment]
Hi aprodhomme I am looking in it right now (got a build error ) with a lastest RAML parser update.

Regards,
Pavel

**Comment by PascalBru** [comment]
I have the same problem like aprodhomme.

@aprodhomme How have you imported the version 0.9-20141227.230728-71 in your pom.xml?

**Comment by aprodhomme** [comment]
Yeah,  I had the dependency to the snapshot of RAML parser  : 

<code>
 `<plugin>`
               <groupId>org.raml.plugins</groupId>
                <artifactId>raml-jaxrs-maven-plugin</artifactId>
                <version>${maven.raml.generator.version}</version>
                <configuration>
                     ...
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.raml</groupId>
                        <artifactId>raml-parser</artifactId>
                        <version>0.9-20141227.230728-71</version>
                    </dependency>
                </dependencies>
        ...
   </plugin>`
</code>

Regards.

**Comment by PascalBru** [comment]
I fixed the problem with adding
```xml
<dependency>
    <groupId>org.jsonschema2pojo</groupId>
    <artifactId>jsonschema2pojo-core</artifactId>
    <version>0.4.5</version>
        <exclusions>
            <exclusion>
	        <artifactId>jackson-databind</artifactId>
                <groupId>com.fasterxml.jackson.core</groupId>
            </exclusion>
        </exclusions>
</dependency>
```

to raml-to-jaxrs\core\pom.xml
